[[redirects]]
  from = "/api/*"
  to = "http://ec2-54-196-185-198.compute-1.amazonaws.com/:splat"
  status = 200
  force = true

# Redirect tất cả route Vue về index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
